default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_learning_platform_development

test:
  <<: *default
  database: ruby_learning_platform_test

production:
  <<: *default
  database: ruby_learning_platform_production
  username: <%= ENV.fetch("DB_USERNAME", "ubuntu") %>
  password: <%= ENV["DB_PASSWORD"] %>
